// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(FicticiaDBContext))]
    [Migration("20210906222627_Creating Bd...")]
    partial class CreatingBd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entities.GenderEntity", b =>
                {
                    b.Property<int>("genderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("genderName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("genderState")
                        .HasColumnType("bit");

                    b.HasKey("genderId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            genderId = 1,
                            genderName = "Masculino",
                            genderState = true
                        },
                        new
                        {
                            genderId = 2,
                            genderName = "Femenino",
                            genderState = true
                        },
                        new
                        {
                            genderId = 3,
                            genderName = "Otro",
                            genderState = true
                        });
                });

            modelBuilder.Entity("Entities.PersonEntity", b =>
                {
                    b.Property<int>("identification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("birthdayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("disease")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isDiabetic")
                        .HasColumnType("bit");

                    b.Property<bool>("isDriver")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("otherDisease")
                        .HasColumnType("bit");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("identification");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            identification = 22452664,
                            birthdayDate = new DateTime(1995, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            disease = "N/A",
                            gender = 1,
                            isActive = true,
                            isDiabetic = false,
                            isDriver = true,
                            name = "Facundo",
                            otherDisease = false,
                            surname = "Roldán"
                        },
                        new
                        {
                            identification = 15447334,
                            birthdayDate = new DateTime(1961, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            disease = "Hipertensión, Asma",
                            gender = 1,
                            isActive = true,
                            isDiabetic = true,
                            isDriver = false,
                            name = "Juan",
                            otherDisease = true,
                            surname = "Perez"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
